stages:
  - install

image: node:18

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies..."
    - cd Backend
    - npm install
